import {
  AccessLog,
  ActiveConsent,
} from "@/features/dashboard/user/types/user-types";

export const mockupAccessLog: AccessLog[] = [
  {
    id: "1",
    user_id: "1",
    accessor_name: "Bank Mandiri",
    accessor_type: "Institusi Keuangan",
    data_accessed: "NIK, Nama, Alamat",
    purpose: "Verifikasi pembukaan rekening",
    access_time: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    user_id: "1",
    accessor_name: "Kementerian Kesehatan",
    accessor_type: "Instansi Pemerintah",
    data_accessed: "NIK, Nama",
    purpose: "Registrasi vaksinasi COVID-19",
    access_time: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    user_id: "1",
    accessor_name: "PT Tokopedia",
    accessor_type: "Platform E-Commerce",
    data_accessed: "NIK, Nama, Nomor Telepon",
    purpose: "Verifikasi akun merchant",
    access_time: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    user_id: "1",
    accessor_name: "PT Gojek Indonesia",
    accessor_type: "Platform Ride-Hailing",
    data_accessed: "NIK, Nama, Foto",
    purpose: "Verifikasi dokumen driver",
    access_time: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    user_id: "1",
    accessor_name: "Bank BCA",
    accessor_type: "Institusi Keuangan",
    data_accessed: "NIK, Nama, Alamat, Pekerjaan",
    purpose: "Pengajuan kartu kredit",
    access_time: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    user_id: "1",
    accessor_name: "PT Shopee International Indonesia",
    accessor_type: "Platform E-Commerce",
    data_accessed: "NIK, Nama, Nomor Telepon",
    purpose: "Aktivasi ShopeePayLater",
    access_time: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "7",
    user_id: "1",
    accessor_name: "BPJS Ketenagakerjaan",
    accessor_type: "Instansi Pemerintah",
    data_accessed: "NIK, Nama, Tanggal Lahir",
    purpose: "Verifikasi klaim JHT",
    access_time: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(),
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "8",
    user_id: "1",
    accessor_name: "PT Traveloka Indonesia",
    accessor_type: "Platform Travel & Hospitality",
    data_accessed: "NIK, Nama, Tanggal Lahir",
    purpose: "Verifikasi booking pesawat internasional",
    access_time: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "9",
    user_id: "1",
    accessor_name: "Bank Mandiri",
    accessor_type: "Institusi Keuangan",
    data_accessed: "NIK, Nama",
    purpose: "Update data nasabah",
    access_time: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "10",
    user_id: "1",
    accessor_name: "PT Tokopedia",
    accessor_type: "Platform E-Commerce",
    data_accessed: "NIK, Alamat",
    purpose: "Verifikasi alamat pengiriman",
    access_time: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "11",
    user_id: "1",
    accessor_name: "PT Gojek Indonesia",
    accessor_type: "Platform Ride-Hailing",
    data_accessed: "NIK, Nomor Telepon",
    purpose: "Update profil mitra",
    access_time: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "12",
    user_id: "1",
    accessor_name: "Kementerian Kesehatan",
    accessor_type: "Instansi Pemerintah",
    data_accessed: "NIK, Nama, Tanggal Lahir",
    purpose: "Verifikasi data peserta PeduliLindungi",
    access_time: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "13",
    user_id: "1",
    accessor_name: "Bank BCA",
    accessor_type: "Institusi Keuangan",
    data_accessed: "NIK, Nama",
    purpose: "Verifikasi transaksi elektronik",
    access_time: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "14",
    user_id: "1",
    accessor_name: "PT Shopee International Indonesia",
    accessor_type: "Platform E-Commerce",
    data_accessed: "NIK, Nama",
    purpose: "Verifikasi seller premium",
    access_time: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(),
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "15",
    user_id: "1",
    accessor_name: "BPJS Ketenagakerjaan",
    accessor_type: "Instansi Pemerintah",
    data_accessed: "NIK, Nama, Alamat",
    purpose: "Verifikasi data kepesertaan",
    access_time: new Date(Date.now() - 1000 * 60 * 60 * 192).toISOString(),
    status: "approved",
    created_at: new Date().toISOString(),
  },
];

export const mockupConsenst: ActiveConsent[] = [
  {
    id: "1",
    user_id: "1",
    organization: "Bank Mandiri",
    organization_type: "Institusi Keuangan",
    data_shared: ["NIK", "Nama Lengkap", "Alamat", "Nomor Telepon"],
    purpose: "Layanan perbankan dan kredit",
    granted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 335).toISOString(),
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    user_id: "1",
    organization: "Kementerian Kesehatan",
    organization_type: "Instansi Pemerintah",
    data_shared: ["NIK", "Nama Lengkap", "Tanggal Lahir"],
    purpose: "Pelayanan kesehatan dan vaksinasi",
    granted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    expires_at: null,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    user_id: "1",
    organization: "PT Tokopedia",
    organization_type: "Platform E-Commerce",
    data_shared: ["NIK", "Nama Lengkap", "Nomor Telepon", "Alamat"],
    purpose: "Layanan jual beli online dan pengiriman",
    granted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 358).toISOString(),
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    user_id: "1",
    organization: "PT Gojek Indonesia",
    organization_type: "Platform Ride-Hailing",
    data_shared: ["NIK", "Nama Lengkap", "Nomor Telepon", "Foto"],
    purpose: "Verifikasi driver dan mitra usaha",
    granted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 320).toISOString(),
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    user_id: "1",
    organization: "Bank BCA",
    organization_type: "Institusi Keuangan",
    data_shared: ["NIK", "Nama Lengkap", "Alamat", "Pekerjaan"],
    purpose: "Pembukaan rekening tabungan dan kartu kredit",
    granted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 305).toISOString(),
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    user_id: "1",
    organization: "PT Shopee International Indonesia",
    organization_type: "Platform E-Commerce",
    data_shared: ["NIK", "Nama Lengkap", "Nomor Telepon"],
    purpose: "Verifikasi seller dan program paylater",
    granted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 351).toISOString(),
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "7",
    user_id: "1",
    organization: "BPJS Ketenagakerjaan",
    organization_type: "Instansi Pemerintah",
    data_shared: ["NIK", "Nama Lengkap", "Tanggal Lahir", "Alamat"],
    purpose: "Pendaftaran dan klaim jaminan sosial",
    granted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
    expires_at: null,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "8",
    user_id: "1",
    organization: "PT Traveloka Indonesia",
    organization_type: "Platform Travel & Hospitality",
    data_shared: ["NIK", "Nama Lengkap", "Tanggal Lahir", "Nomor Telepon"],
    purpose: "Booking hotel, tiket pesawat dan verifikasi penumpang",
    granted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 362).toISOString(),
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "9",
    user_id: "1",
    organization: "PT Grab Indonesia",
    organization_type: "Platform Ride-Hailing",
    data_shared: ["NIK", "Nama Lengkap", "Nomor Telepon", "Alamat"],
    purpose: "Layanan transportasi dan GrabFood",
    granted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 345).toISOString(),
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "10",
    user_id: "1",
    organization: "PT Bukalapak.com",
    organization_type: "Platform E-Commerce",
    data_shared: ["NIK", "Nama Lengkap", "Nomor Telepon"],
    purpose: "Verifikasi seller dan program BukaDompet",
    granted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 330).toISOString(),
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "11",
    user_id: "1",
    organization: "PT Visionet Internasional (OVO)",
    organization_type: "Fintech & E-Wallet",
    data_shared: ["NIK", "Nama Lengkap", "Tanggal Lahir", "Nomor Telepon"],
    purpose: "Verifikasi premium account dan limit upgrade",
    granted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 50).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 315).toISOString(),
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "12",
    user_id: "1",
    organization: "PT Fintek Karya Nusantara (LinkAja)",
    organization_type: "Fintech & E-Wallet",
    data_shared: ["NIK", "Nama Lengkap", "Alamat", "Nomor Telepon"],
    purpose: "Upgrade akun dan peningkatan limit transaksi",
    granted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 340).toISOString(),
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "13",
    user_id: "1",
    organization: "PT Indonesia Digital Identity (VIDA)",
    organization_type: "Digital Identity Provider",
    data_shared: ["NIK", "Nama Lengkap", "Tanggal Lahir", "Foto", "Alamat"],
    purpose: "Verifikasi identitas digital dan layanan tanda tangan elektronik",
    granted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 80).toISOString(),
    expires_at: null,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "14",
    user_id: "1",
    organization: "PT Global Digital Niaga (Blibli)",
    organization_type: "Platform E-Commerce",
    data_shared: ["NIK", "Nama Lengkap", "Nomor Telepon", "Alamat"],
    purpose: "Verifikasi merchant dan program tiket installment",
    granted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 353).toISOString(),
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "15",
    user_id: "1",
    organization: "PT Kredivo Fintek Indonesia",
    organization_type: "Fintech & Lending",
    data_shared: [
      "NIK",
      "Nama Lengkap",
      "Pekerjaan",
      "Alamat",
      "Nomor Telepon",
    ],
    purpose: "Persetujuan kredit dan cicilan belanja online",
    granted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 325).toISOString(),
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
