/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authenticatedDashboardRouteRouteImport } from './routes/(authenticated)/dashboard/route'
import { Route as authenticatedAdminRouteRouteImport } from './routes/(authenticated)/admin/route'
import { Route as authenticatedDashboardIndexRouteImport } from './routes/(authenticated)/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatedDashboardSettingsRouteImport } from './routes/(authenticated)/dashboard/settings'
import { Route as authenticatedDashboardProfileRouteImport } from './routes/(authenticated)/dashboard/profile'
import { Route as authenticatedDashboardEditProfileRouteImport } from './routes/(authenticated)/dashboard/edit-profile'
import { Route as authenticatedDashboardActivityMonitoringRouteImport } from './routes/(authenticated)/dashboard/activity-monitoring'
import { Route as authenticatedAdminDashboardRouteImport } from './routes/(authenticated)/admin/dashboard'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authenticatedDashboardRouteRoute =
  authenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAdminRouteRoute = authenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedDashboardIndexRoute =
  authenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedDashboardSettingsRoute =
  authenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardProfileRoute =
  authenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardEditProfileRoute =
  authenticatedDashboardEditProfileRouteImport.update({
    id: '/edit-profile',
    path: '/edit-profile',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardActivityMonitoringRoute =
  authenticatedDashboardActivityMonitoringRouteImport.update({
    id: '/activity-monitoring',
    path: '/activity-monitoring',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedAdminDashboardRoute =
  authenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof authenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/admin/dashboard': typeof authenticatedAdminDashboardRoute
  '/dashboard/activity-monitoring': typeof authenticatedDashboardActivityMonitoringRoute
  '/dashboard/edit-profile': typeof authenticatedDashboardEditProfileRoute
  '/dashboard/profile': typeof authenticatedDashboardProfileRoute
  '/dashboard/settings': typeof authenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof authenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof authenticatedAdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/admin/dashboard': typeof authenticatedAdminDashboardRoute
  '/dashboard/activity-monitoring': typeof authenticatedDashboardActivityMonitoringRoute
  '/dashboard/edit-profile': typeof authenticatedDashboardEditProfileRoute
  '/dashboard/profile': typeof authenticatedDashboardProfileRoute
  '/dashboard/settings': typeof authenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/admin': typeof authenticatedAdminRouteRouteWithChildren
  '/(authenticated)/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(authenticated)/admin/dashboard': typeof authenticatedAdminDashboardRoute
  '/(authenticated)/dashboard/activity-monitoring': typeof authenticatedDashboardActivityMonitoringRoute
  '/(authenticated)/dashboard/edit-profile': typeof authenticatedDashboardEditProfileRoute
  '/(authenticated)/dashboard/profile': typeof authenticatedDashboardProfileRoute
  '/(authenticated)/dashboard/settings': typeof authenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(authenticated)/dashboard/': typeof authenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/dashboard/activity-monitoring'
    | '/dashboard/edit-profile'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/dashboard/activity-monitoring'
    | '/dashboard/edit-profile'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(authenticated)'
    | '/(authenticated)/admin'
    | '/(authenticated)/dashboard'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(authenticated)/admin/dashboard'
    | '/(authenticated)/dashboard/activity-monitoring'
    | '/(authenticated)/dashboard/edit-profile'
    | '/(authenticated)/dashboard/profile'
    | '/(authenticated)/dashboard/settings'
    | '/api/auth/$'
    | '/(authenticated)/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/admin': {
      id: '/(authenticated)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authenticatedAdminRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/dashboard/': {
      id: '/(authenticated)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedDashboardIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard/settings': {
      id: '/(authenticated)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof authenticatedDashboardSettingsRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/profile': {
      id: '/(authenticated)/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof authenticatedDashboardProfileRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/edit-profile': {
      id: '/(authenticated)/dashboard/edit-profile'
      path: '/edit-profile'
      fullPath: '/dashboard/edit-profile'
      preLoaderRoute: typeof authenticatedDashboardEditProfileRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/activity-monitoring': {
      id: '/(authenticated)/dashboard/activity-monitoring'
      path: '/activity-monitoring'
      fullPath: '/dashboard/activity-monitoring'
      preLoaderRoute: typeof authenticatedDashboardActivityMonitoringRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/admin/dashboard': {
      id: '/(authenticated)/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof authenticatedAdminDashboardRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface authenticatedAdminRouteRouteChildren {
  authenticatedAdminDashboardRoute: typeof authenticatedAdminDashboardRoute
}

const authenticatedAdminRouteRouteChildren: authenticatedAdminRouteRouteChildren =
  {
    authenticatedAdminDashboardRoute: authenticatedAdminDashboardRoute,
  }

const authenticatedAdminRouteRouteWithChildren =
  authenticatedAdminRouteRoute._addFileChildren(
    authenticatedAdminRouteRouteChildren,
  )

interface authenticatedDashboardRouteRouteChildren {
  authenticatedDashboardActivityMonitoringRoute: typeof authenticatedDashboardActivityMonitoringRoute
  authenticatedDashboardEditProfileRoute: typeof authenticatedDashboardEditProfileRoute
  authenticatedDashboardProfileRoute: typeof authenticatedDashboardProfileRoute
  authenticatedDashboardSettingsRoute: typeof authenticatedDashboardSettingsRoute
  authenticatedDashboardIndexRoute: typeof authenticatedDashboardIndexRoute
}

const authenticatedDashboardRouteRouteChildren: authenticatedDashboardRouteRouteChildren =
  {
    authenticatedDashboardActivityMonitoringRoute:
      authenticatedDashboardActivityMonitoringRoute,
    authenticatedDashboardEditProfileRoute:
      authenticatedDashboardEditProfileRoute,
    authenticatedDashboardProfileRoute: authenticatedDashboardProfileRoute,
    authenticatedDashboardSettingsRoute: authenticatedDashboardSettingsRoute,
    authenticatedDashboardIndexRoute: authenticatedDashboardIndexRoute,
  }

const authenticatedDashboardRouteRouteWithChildren =
  authenticatedDashboardRouteRoute._addFileChildren(
    authenticatedDashboardRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedAdminRouteRoute: typeof authenticatedAdminRouteRouteWithChildren
  authenticatedDashboardRouteRoute: typeof authenticatedDashboardRouteRouteWithChildren
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedAdminRouteRoute: authenticatedAdminRouteRouteWithChildren,
  authenticatedDashboardRouteRoute:
    authenticatedDashboardRouteRouteWithChildren,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
